language: python
python:
  - '2.7'
  - '3.4'
before_install:
  - sudo apt-get install r-base
  - Rscript -e 'install.packages("pROC")'
install:
  - 'pip install coveralls'
  - 'python setup.py install'
script: 
  - py.test
  - coverage run --source=ml-tools -m py.test
after_success:
  - coveralls
sudo: True
