language: python
addons:
  apt:
    packages:
      - r-base
python:
  - '2.7'
  - '3.4'
before_install:
  - Rscript -e 'install.packages("pROC", lib="/home/travis/R-bin/lib/R/library/")'
install:
  - 'pip install coveralls'
  - 'python setup.py install'
script: 
  - py.test
  - coverage run --source=ml-tools -m py.test
after_success:
  - coveralls
sudo: True
