language: r, python
addons:
  apt:
    packages:
      - gfortran
r:
  - release
env:
  - R_LIBS_USER=~/R/library
cache:
  directories:
    $R_LIBS_USER
python:
  - '2.7'
  - '3.4'
before_install:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'install.packages("ggplot2", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("pROC", dependencies = TRUE, repos = "http://cran.us.r-project.org")'
install:
  - 'pip install coveralls'
  - 'python setup.py install'
script: 
  - py.test
  - coverage run --source=ml-tools -m py.test
after_success:
  - coveralls
sudo: True
